[package]
name = "boids_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou = "0.18.1"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
